GET http://localhost:3000/study/eddc1d7a-8ac3-4e1c-be36-cb9d2c5dea9c/habit

###
POST http://localhost:3000/study/eddc1d7a-8ac3-4e1c-be36-cb9d2c5dea9c/habit
Content-Type: application/json

{
  "name": "React 개념 정리하기"
}

###
PATCH http://localhost:3000/habit/fb87889b-350e-4251-9e68-c357af3a5291
Content-Type: application/json

{
  "name": "알고리즘 2문제 풀기"
}

###
DELETE http://localhost:3000/

###
POST http://localhost:3000/study/eddc1d7a-8ac3-4e1c-be36-cb9d2c5dea9c/habit/00bd04a7-815d-415d-b2c7-d11f367b4541/record

###
PATCH http://localhost:3000/study/eddc1d7a-8ac3-4e1c-be36-cb9d2c5dea9c/habit/record/b2c01f70-3957-455f-8988-5d2e38a65f7f